In [2]:
import torch
import numpy

In [ ]:
# Gradient Calculation with Autograd

In [3]:
x = torch.rand(3, requires_grad = True)
print(x)


tensor([0.1176, 0.5274, 0.5873], requires_grad=True)


In [14]:
y = x + 2 # this will create a computational graph
print(y)

z = y*y*2 # not a scaler
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([2.1176, 2.5274, 2.5873], grad_fn=<AddBackward0>)
tensor([ 7.9055, 64.0284,  3.5118])


In [15]:
z = y*y*2
z = z.mean() # a scaler
z.backward() # dz/dx
print(x.grad)

tensor([10.7290, 67.3983,  6.9616])


In [17]:

# no gradient calculation
print(x)

# solution 1
y = x.detach()
print(y)

# solution 2
with torch.no_grad():
    y = x + 2
    print(y)

# solution 3
x.requires_grad_(False)
print(x)

tensor([0.1176, 0.5274, 0.5873], requires_grad=True)
tensor([0.1176, 0.5274, 0.5873])
tensor([2.1176, 2.5274, 2.5873])
tensor([0.1176, 0.5274, 0.5873])


In [21]:

# not desired. The gradients are tracked.
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [23]:
# Desired
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [25]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()